### ISSUE TITLE
Release 1.1.5 and git regression

### ISSUE THREAD

**Issue by bhuisgen** [adubkov/py-zabbix#125]
There is some problems about the git management on this project & the pypi packages releases. 

I did the PR #119 merged for the release 1.1.5 so there was the git branch "release-1.1.5". But the next PR merge on this branch reintroduces old code and revert my fixes.

In addition to that if you check your pypi package 1.1.5, its content doesn't fit the version from the release branch (check this file: https://github.com/adubkov/py-zabbix/blob/release-1.1.5/pyzabbix/sender.py). It seems that the pip content was from the master branch.

I can of course recreate a new PR but please be careful. Right now I have the same reconnection problem as the previous release: my agents stopped to send metrics as the server has been simply upgraded. A generic exception is raised from code (which is bad) and it has ended all my sending threads:

```
2019-09-25T11:16:18.765877380Z zabbix-agent.0.7asa483dbvnx@node    | Exception in thread Thread-30:
2019-09-25T11:16:18.765880649Z zabbix-agent.0.7asa483dbvnx@node    | Traceback (most recent call last):
2019-09-25T11:16:18.765885963Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/pyzabbix/sender.py", line 398, in _chunk_send
2019-09-25T11:16:18.765891031Z zabbix-agent.0.7asa483dbvnx@node    |     connection.connect(host_addr)
2019-09-25T11:16:18.765916043Z zabbix-agent.0.7asa483dbvnx@node    | ConnectionRefusedError: [Errno 111] Connection refused
2019-09-25T11:16:18.765920133Z zabbix-agent.0.7asa483dbvnx@node    |
2019-09-25T11:16:18.765923246Z zabbix-agent.0.7asa483dbvnx@node    | During handling of the above exception, another exception occurred:
2019-09-25T11:16:18.765927220Z zabbix-agent.0.7asa483dbvnx@node    |
2019-09-25T11:16:18.765930393Z zabbix-agent.0.7asa483dbvnx@node    | Traceback (most recent call last):
2019-09-25T11:16:18.765933610Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/threading.py", line 917, in _bootstrap_inner
2019-09-25T11:16:18.765937051Z zabbix-agent.0.7asa483dbvnx@node    |     self.run()
2019-09-25T11:16:18.765940130Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/zabbixdocker/services/swarm.py", line 853, in run
2019-09-25T11:16:18.765943553Z zabbix-agent.0.7asa483dbvnx@node    |     self._zabbix_sender.send(metrics)
2019-09-25T11:16:18.765946790Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/pyzabbix/sender.py", line 433, in send
2019-09-25T11:16:18.765950395Z zabbix-agent.0.7asa483dbvnx@node    |     result.parse(self._chunk_send(metrics[m:m + self.chunk_size]))
2019-09-25T11:16:18.765953576Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/pyzabbix/sender.py", line 408, in _chunk_send
2019-09-25T11:16:18.765957177Z zabbix-agent.0.7asa483dbvnx@node    |     logger.warn('Sending failed: %s', err.msg)
2019-09-25T11:16:18.765960403Z zabbix-agent.0.7asa483dbvnx@node    | AttributeError: 'ConnectionRefusedError' object has no attribute 'msg'
2019-09-25T11:16:18.765963584Z zabbix-agent.0.7asa483dbvnx@node    |
2019-09-25T11:16:18.765966748Z zabbix-agent.0.7asa483dbvnx@node    | Exception in thread Thread-24:
2019-09-25T11:16:18.765970058Z zabbix-agent.0.7asa483dbvnx@node    | Traceback (most recent call last):
2019-09-25T11:16:18.765973741Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/pyzabbix/sender.py", line 398, in _chunk_send
2019-09-25T11:16:18.765977092Z zabbix-agent.0.7asa483dbvnx@node    |     connection.connect(host_addr)
2019-09-25T11:16:18.765984206Z zabbix-agent.0.7asa483dbvnx@node    | ConnectionRefusedError: [Errno 111] Connection refused
2019-09-25T11:16:18.765987654Z zabbix-agent.0.7asa483dbvnx@node    |
2019-09-25T11:16:18.765990835Z zabbix-agent.0.7asa483dbvnx@node    | During handling of the above exception, another exception occurred:
2019-09-25T11:16:18.765994195Z zabbix-agent.0.7asa483dbvnx@node    |
2019-09-25T11:16:18.765997351Z zabbix-agent.0.7asa483dbvnx@node    | Traceback (most recent call last):
2019-09-25T11:16:18.766000694Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/threading.py", line 917, in _bootstrap_inner
2019-09-25T11:16:18.766004908Z zabbix-agent.0.7asa483dbvnx@node    |     self.run()
2019-09-25T11:16:18.766008172Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/zabbixdocker/services/volumes.py", line 115, in run
2019-09-25T11:16:18.766011977Z zabbix-agent.0.7asa483dbvnx@node    |     self._zabbix_sender.send(metrics)
2019-09-25T11:16:18.766015270Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/pyzabbix/sender.py", line 433, in send
2019-09-25T11:16:18.766018585Z zabbix-agent.0.7asa483dbvnx@node    |     result.parse(self._chunk_send(metrics[m:m + self.chunk_size]))
2019-09-25T11:16:18.766021876Z zabbix-agent.0.7asa483dbvnx@node    |   File "/opt/python/lib/python3.7/site-packages/pyzabbix/sender.py", line 408, in _chunk_send
2019-09-25T11:16:18.766025290Z zabbix-agent.0.7asa483dbvnx@node    |     logger.warn('Sending failed: %s', err.msg)
2019-09-25T11:16:18.766028554Z zabbix-agent.0.7asa483dbvnx@node    | AttributeError: 'ConnectionRefusedError' object has no attribute 'msg'
2019-09-26T00:28:41.752618106Z zabbix-agent.0.7asa483dbvnx@node    |     39:20190926:002841.751 Executing command 'HOME=/var/lib/zabbix /usr/bin/puppet agent --version'
```

My code which excepts OSError exceptions: https://github.com/bhuisgen/zabbix-docker/blob/4df90647400b8f3e681bbd82d724a02aea8b69ed/zabbixdocker/services/containers.py#L196

My "previous" fix for py-zabbix : https://github.com/adubkov/py-zabbix/pull/119/commits/e1f80e4c5d5648a77487b502bcdd4be87957f8d3

**Comment by adubkov** [comment]
Hi, 

You are right, pip package was accidentally build from master branch. I just merge release into master, bump the version to 1.1.6 and tag it. Pip also has 1.1.6 for both py2 and py3 now.
